name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m venv scraper
          source scraper/bin/activate
          make install
          
      - name: Verify Pylint
        run: | 
          pip install pylint
          pylint --version
  
      - name: Lint data_scraper.py
        run: |
          make lint_data_scraper

      - name: Lint data_test.py
        run: |
          make lint_data_test

      - name: Test data_scraper.py
        run: |
          make test_data_scraper

      - name: Test data_test.py
        run: |
          make test_data_test


          
    
